apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-4
  labels:
    app: hola-mundo-4
spec:
  selector:
    app: hola-mundo-4
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: NodePort